---
- name: Update user password on multiple servers
  hosts: all
  become: yes
  gather_facts: no
  vars_prompt:
    - name: num_chars
      prompt: "Enter the number of characters for the password"
      private: no
    - name: username
      prompt: "Enter the username"
      private: no
  tasks:
    - name: Check if user exists
      command: id {{ username }}
      register: user_exists
      ignore_errors: yes
    - name: Fail if user does not exist
      fail:
        msg: "User {{ username }} does not exist on server {{ inventory_hostname }}"
      when: user_exists.rc != 0
    - name: Generate and encrypt password locally
      local_action: command /home/svc_ans/playbooks/files/change_remote_account.sh {{ num_chars }} {{ username }} {{ inventory_hostname }}
      register: local_password
    - name: Update the user's password on the remote server
      user:
        name: "{{ username }}"
        password: "{{ local_password.stdout_lines[-1] }}"
        update_password: always
