---
- name: Remove password from local user account
  hosts: all
  become: yes
  gather_facts: no
  vars_prompt:
    - name: username
      prompt: "Enter the username to remove password from"
      private: no
      
  tasks:
    - name: Check if user exists
      command: id {{ username }}
      register: user_exists
      ignore_errors: yes
      
    - name: Display message if user does not exist
      debug:
        msg: "User '{{ username }}' does NOT exist on server {{ inventory_hostname }}, so nothing was changed."
      when: user_exists.rc != 0
      
    - name: Check if user has a password set
      shell: "getent shadow {{ username }} | cut -d: -f2"
      register: user_password_field
      ignore_errors: yes
      when: user_exists.rc == 0
      
    - name: Display message if user has no password or is already locked
      debug:
        msg: "User '{{ username }}' on server {{ inventory_hostname }} has no password set or is already locked, so nothing was changed."
      when: 
        - user_exists.rc == 0
        - user_password_field.stdout == "" or user_password_field.stdout == "!" or user_password_field.stdout == "*"
        
    - name: Remove password from user account
      command: passwd -d {{ username }}
      register: password_removal
      when: 
        - user_exists.rc == 0
        - user_password_field.stdout != ""
        - user_password_field.stdout != "!"
        - user_password_field.stdout != "*"
        
    - name: Display success message
      debug:
        msg: "Password successfully removed for user '{{ username }}' on server {{ inventory_hostname }}."
      when: 
        - user_exists.rc == 0
        - user_password_field.stdout != ""
        - user_password_field.stdout != "!"
        - user_password_field.stdout != "*"
        - password_removal is defined
        
    - name: Get current timestamp
      local_action: command date "+%Y-%m-%dT%H:%M:%S"
      register: current_timestamp
      when: 
        - user_exists.rc == 0
        - user_password_field.stdout != ""
        - user_password_field.stdout != "!"
        - user_password_field.stdout != "*"
        - password_removal is defined
        
    - name: Log password removal action
      local_action:
        module: lineinfile
        path: /home/svc_ans/playbooks/files/password_removal_log.csv
        line: "{{ inventory_hostname }},{{ username }},{{ current_timestamp.stdout }},password_removed"
        create: yes
      when: 
        - user_exists.rc == 0
        - user_password_field.stdout != ""
        - user_password_field.stdout != "!"
        - user_password_field.stdout != "*"
        - password_removal is defined
        
    - name: Display log file location
      debug:
        msg: "Password removal action has been logged to: /home/svc_ans/playbooks/files/password_removal_log.csv"
      when: 
        - user_exists.rc == 0
        - user_password_field.stdout != ""
        - user_password_field.stdout != "!"
        - user_password_field.stdout != "*"
        - password_removal is defined
