---
- name: Update user password with unique passwords per server
  hosts: all
  become: yes
  gather_facts: no
  serial: 5  # Process 5 servers at a time to avoid overwhelming
  vars_prompt:
    - name: num_chars
      prompt: "Enter the number of characters for the password"
      private: no
    - name: username
      prompt: "Enter the username"
      private: no
  tasks:
    - name: Check if user exists
      command: id {{ username }}
      register: user_exists
      ignore_errors: yes
      
    - name: Fail if user does not exist
      fail:
        msg: "User {{ username }} does not exist on server {{ inventory_hostname }}"
      when: user_exists.rc != 0
      
    - name: Generate unique password for this server
      local_action: command /home/svc_ans/playbooks/files/change_remote_account.sh {{ num_chars }} {{ username }} {{ inventory_hostname }}
      register: server_password
      
    - name: Update the user's password on the remote server
      user:
        name: "{{ username }}"
        password: "{{ server_password.stdout_lines[-1] }}"
        update_password: always
        
    - name: Record rotation date
      local_action: 
        module: lineinfile
        path: /home/svc_ans/playbooks/files/password_rotation_log.csv
        line: "{{ inventory_hostname }},{{ username }},{{ ansible_date_time.iso8601 }}"
        create: yes
