---
all:
  children:
    central_server:
      hosts:
        10.10.10.96:  # ser8 - your ansible server
          ansible_user: brian
          ansible_ssh_private_key_file: /home/brian/.ssh/id_ed25519
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_python_interpreter: /usr/bin/python3
